name: Build Trampoline Release

on:
  push:
    tags:
      - '*'  # Run only when a tag is pushed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake (Visual Studio generator)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A Win32

      - name: Build the project (Release)
        run: cmake --build build --config Release
        
      - name: Copy EnergyPlus workbook into build folder
        run: copy ExcellingEnergyPlus.xlsm build/Release
      
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: Trampoline-32bit-with-workbook
          path: |
            build/Release/trampoline.dll
            build/Release/ExcellingEnergyPlus.xlsm
